name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/SplitPe-GodiyalStore.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SplitPe-Shop-APK
          path: build/app/outputs/flutter-apk/SplitPe-GodiyalStore.apk

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: "SplitPe - Godiyal General Store v1.0.0"
          body: |
            ### 🛒 SplitPe customized for Godiyal General Store
            - **Merchant UPI ID**: `Q865308672@ybl`
            - **Shop Name**: `Godiyal General Store`
            
            Click below to download the APK directly:
            👉 **[SplitPe-GodiyalStore.apk](https://github.com/ayushgodiyal40/SplitPe/releases/download/v1.0.0/SplitPe-GodiyalStore.apk)**
          files: build/app/outputs/flutter-apk/SplitPe-GodiyalStore.apk
